"""E2E: ``ai-hats reflect all`` builds the handoff + launches the judge.

User-way (HATS-546 / S-CLI-26)
------------------------------

End of a long work session. I have several open hypotheses and
pending proposals accumulated. I want to triage them in one sitting
without manually opening every YAML. I run:

    ai-hats reflect all

Pre-flight (Python) builds a handoff markdown file listing every open
HYP + PROP under ``<ai_hats_dir>/sessions/retros/reflect-all/<ts>-handoff.md``.
Stdout prints ``Handoff written: <path>``. Then an interactive
``judge`` session launches — I'm now in a chat with the judge who
triages each item with me. I close items, defer others, and exit via
``/exit`` when done.

What this test pins (entry-point sanity)
-----------------------------------------

1. The bare ``reflect all`` invocation runs without crashing under
   non-TTY subprocess input (stdin = ``DEFAULT_EXIT_PAYLOAD``).
2. Pre-flight handoff lands on disk at the documented path with
   non-zero size — proves the Python prelude (HYP/PROP enumeration +
   markdown render) executed.
3. Stdout (ANSI-stripped) carries the ``Handoff written:`` line —
   the user's visual confirmation that the artefact was emitted.
4. The PTY session exits cleanly (exit code in ``{0, 130}`` — 130
   is the SIGINT teardown signature from the ``/exit`` payload).
5. No Python ``Traceback`` leaks to user-facing output.

What this test does NOT pin
---------------------------

- The interactive triage outcome (HYP closures, PROP state
  transitions). Those require a multi-turn HITL chat — HATS-544
  territory once HATS-529 / HATS-530 land.
- Handoff content beyond "non-empty" — the markdown body is
  generated by a Python loop over the stores; not LLM-driven.

Fixture choice: ``tmp_project`` (dev venv) + real HOME claude auth.
Same rationale as ``test_reflect_issue_e2e.py``.
"""

from __future__ import annotations

import pytest

from _helpers.hitl import drive_bare_hitl, strip_ansi
from _helpers.project import Project


pytestmark = pytest.mark.integration


# PTY launch + Python pre-flight + claude TUI splash + ``/exit``
# teardown ≈ 10-20s on warm cache; envelope buffer for cold network.
REFLECT_ALL_TIMEOUT = 30.0


def test_reflect_all_builds_handoff_and_launches_judge(
    tmp_project: Project,
    requires_claude_auth,  # noqa: ARG001 — skip-marker fixture
) -> None:
    """User-way smoke: handoff on disk + clean PTY exit."""
    result = drive_bare_hitl(
        tmp_project,
        subcommand_args=("reflect", "all"),
        timeout=REFLECT_ALL_TIMEOUT,
    ).expect_no_hang().expect_exit_in({0, 130})

    # ---- Pre-flight artefact (deterministic, Python-side) ----
    plain = strip_ansi(result.stdout)
    assert "Handoff written:" in plain, (
        "stdout missing the pre-flight handoff confirmation line — "
        "did reflect_all_cmd short-circuit before _build_handoff?\n"
        f"stdout (tail 800):\n{plain[-800:]}"
    )

    handoff_dir = (
        tmp_project.agent_dir / "sessions" / "retros" / "reflect-all"
    )
    handoffs = list(handoff_dir.glob("*-handoff.md"))
    assert len(handoffs) == 1, (
        f"expected exactly one handoff under {handoff_dir}, "
        f"got {len(handoffs)}: {handoffs}"
    )
    assert handoffs[0].stat().st_size > 0, (
        f"handoff file is empty: {handoffs[0]}"
    )

    # ---- Pin that we actually got past the pre-flight into PTY ----
    # Without this assertion the test would silently pass if
    # reflect_all_cmd returned before claude exec (e.g. an accidental
    # ``return`` after _build_handoff or a regression that re-routes
    # the dry-run logic). The session-start banner is printed by
    # ``runtime._print_session_start`` only AFTER WrapRunner is
    # constructed → strong proof claude was actually spawned.
    assert "Launching judge" in plain, (
        "reflect all did not advance past pre-flight to launch judge — "
        f"regression in reflect_all_cmd?\nstdout (tail 800):\n{plain[-800:]}"
    )
    assert "Session:" in plain, (
        "session-start banner missing — WrapRunner did not spawn?\n"
        f"stdout (tail 800):\n{plain[-800:]}"
    )

    # ---- Defensive: no traceback leak ----
    assert "Traceback" not in plain, (
        f"traceback leaked to user-facing output:\n"
        f"stdout (tail 800):\n{plain[-800:]}"
    )
