"""Acceptance: the printed remedy, followed verbatim, actually fixes the hook (HATS-1245).

``assert "PATH=" in msg`` is satisfied by any five characters — including a line
that is subtly wrong, points at the wrong directory, or is not copy-pasteable.
The defect this file guards is precisely *"the printed instructions do not work
when followed"*, which no assertion on the string can catch. So the commands are
not re-typed here: they are **extracted from the message itself** and executed
against a real git worktree with the real smoke hook installed, and the test
asserts which interpreter the hook ended up spawning.

Both halves matter. Without the PATH step the hook must still resolve a foreign
interpreter (that is the bug HATS-1245 reported); with it, the worktree's own.
The negative half is what proves the added line is load-bearing rather than
decorative — drop it from ``remedy_message`` and this file goes red.

Fidelity vs cost: the repo under test is synthetic and its ``[dev]`` extra is
just pytest, so the remedy's commands run verbatim in seconds instead of the
minutes a full ai-hats dependency tree would take. What is under test — the
literal printed commands, the real hook script, a real ``git commit`` — is
unchanged.

Deliberate long contract module docstring — noqa: comment-length.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import pytest

from _helpers.env import clean_env
from _helpers.venv import network_available, venv_unavailable
from tests._checkout_guard import remedy_message

pytestmark = [pytest.mark.integration, pytest.mark.install_heavy]

PROBE_ENV = "HATS1245_PROBE"

# The library file, not the installed `.githooks/` copy: `.githooks/` is
# generated by composition and gitignored, so it is absent in a worktree and in
# a fresh clone — depending on it made this whole file skip (a false green).
SMOKE_HOOK = Path(
    "packages/ai-hats-library/src/ai_hats_library/core/skills/git-mastery"
    "/git_hooks/pre-commit-smoke.sh"
)

PYPROJECT = """\
[project]
name = "wtprobe"
version = "0"

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools]
packages = ["wtprobe"]

[tool.pytest.ini_options]
markers = ["smoke: the marker the pre-commit gate selects on"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
"""

# Records the interpreter the hook spawned. Reading sys.executable from inside
# the hook-run pytest is the only unambiguous answer to "which checkout ran?".
PROBE_TEST = f"""\
import os
import pathlib
import sys

import pytest


@pytest.mark.smoke
def test_record_the_interpreter_that_ran_me():
    pathlib.Path(os.environ["{PROBE_ENV}"]).write_text(sys.executable)
"""

TASK_YAML = """\
id: HATS-9999
title: arms the smoke gate
state: execute
tags:
  - integration
"""


@dataclass(frozen=True)
class Sandbox:
    main: Path
    wt: Path
    msg: str
    probe: Path


def _git(cwd: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args], cwd=cwd, check=True, capture_output=True, text=True, timeout=60
    )


def _bash(script: str, cwd: Path, env: dict[str, str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", "-c", script], cwd=cwd, env=env, capture_output=True, text=True, timeout=600
    )


def remedy_commands(msg: str, prefix: str) -> list[str]:
    """The runnable lines of the printed remedy that start with ``prefix``.

    Extracted, never re-typed: a test that retypes the commands would keep
    passing after the message stopped printing them.
    """
    return [
        line.strip()
        for line in msg.splitlines()
        if line.startswith("  ") and line.strip().startswith(prefix)
    ]


def _one(msg: str, prefix: str) -> str:
    found = remedy_commands(msg, prefix)
    assert len(found) == 1, f"expected exactly one {prefix!r} line in the remedy, got {found}"
    return found[0]


@pytest.fixture(scope="module")
def sandbox(tmp_path_factory: pytest.TempPathFactory, repo_root: Path) -> Sandbox:
    """A synthetic repo + worktree, provisioned by the remedy's own step 1."""
    hook_src = repo_root / SMOKE_HOOK
    if not hook_src.is_file():
        # Tracked file — absence is a moved/renamed hook, never an environment
        # condition. Skipping here would silently retire the acceptance test.
        pytest.fail(f"smoke hook source moved — update SMOKE_HOOK: {hook_src}", pytrace=False)
    if not network_available():
        venv_unavailable("uv is not on PATH — cannot run the remedy's install step")

    root = tmp_path_factory.mktemp("remedy")
    main, wt = root / "main", root / "wt"
    main.mkdir()

    (main / "pyproject.toml").write_text(PYPROJECT)
    (main / "wtprobe").mkdir()
    (main / "wtprobe" / "__init__.py").touch()
    (main / "tests").mkdir()
    (main / "tests" / "test_probe.py").write_text(PROBE_TEST)
    (main / ".gitignore").write_text(".venv/\n.agent/\n")

    _git(main, "init", "-b", "master")
    _git(main, "config", "user.email", "t@e")
    _git(main, "config", "user.name", "T")
    _git(main, "add", "-A")
    _git(main, "commit", "-m", "init")

    # Arm AFTER the initial commit: an armed gate would fire on it.
    tasks = main / ".agent" / "ai-hats" / "tracker" / "backlog" / "tasks" / "HATS-9999"
    tasks.mkdir(parents=True)
    (tasks / "task.yaml").write_text(TASK_YAML)

    hooks = root / "hooks"
    hooks.mkdir()
    shutil.copy2(hook_src, hooks / "pre-commit")
    (hooks / "pre-commit").chmod(0o755)
    _git(main, "config", "core.hooksPath", str(hooks))

    _git(main, "worktree", "add", str(wt), "-b", "probe")

    msg = remedy_message(wt, main)
    env = clean_env(os.environ)
    for cmd in (_one(msg, "uv venv"), _one(msg, "VIRTUAL_ENV=")):
        res = _bash(cmd, cwd=wt, env=env)
        if res.returncode != 0:
            venv_unavailable(f"remedy step 1 failed ({cmd!r}): {res.stderr[-400:]}")

    return Sandbox(main=main, wt=wt, msg=msg, probe=root / "probe.txt")


def _commit_and_read_probe(sandbox: Sandbox, name: str, preamble: str = "") -> Path:
    """Make a change, commit it through the real hook, return what the hook ran."""
    (sandbox.wt / name).write_text("x\n")
    env = clean_env(os.environ)
    env[PROBE_ENV] = str(sandbox.probe)
    sandbox.probe.unlink(missing_ok=True)

    _git(sandbox.wt, "add", "-A")
    res = _bash(f'{preamble}git commit -m "{name}"', cwd=sandbox.wt, env=env)
    assert res.returncode == 0, f"commit blocked: {res.stdout}\n{res.stderr}"
    assert sandbox.probe.is_file(), (
        f"the smoke gate never ran — nothing to measure.\n{res.stdout}\n{res.stderr}"
    )
    return Path(sandbox.probe.read_text().strip())


def test_provisioning_alone_leaves_the_hook_on_a_foreign_interpreter(sandbox: Sandbox) -> None:
    """The bug: step 1 followed, step 2 skipped — the gate still runs elsewhere."""
    ran = _commit_and_read_probe(sandbox, "a.txt")
    assert sandbox.wt not in ran.parents, (
        f"expected the hook to miss the worktree venv without the PATH step, but it used {ran}"
    )


def test_the_printed_path_line_makes_the_hook_use_the_worktree(sandbox: Sandbox) -> None:
    """Acceptance (b): the remedy's own PATH line, executed, fixes the gate."""
    export = _one(sandbox.msg, "export PATH=")
    ran = _commit_and_read_probe(sandbox, "b.txt", preamble=f"{export}\n")
    assert sandbox.wt in ran.parents, (
        f"the remedy's PATH line did not redirect the hook to the worktree venv: {ran}"
    )


def test_the_one_shot_form_is_runnable_as_printed(sandbox: Sandbox) -> None:
    """The second form is a copy-paste prefix, so it must survive substitution."""
    one_shot = _one(sandbox.msg, "PATH=")
    assert one_shot.endswith("git commit ...")
    prefix = one_shot.removesuffix("git commit ...")
    ran = _commit_and_read_probe(sandbox, "c.txt", preamble=prefix)
    assert sandbox.wt in ran.parents, (
        f"the one-shot form did not redirect the hook to the worktree venv: {ran}"
    )
