vars: @./_palette

direction: right

open
accepted {shape: oval}
rejected {shape: oval}
deferred {shape: oval}
duplicate {shape: oval}

open -> accepted
open -> rejected
open -> deferred
open -> duplicate
