"""SessionRetroV1: descriptive snapshot of one session.

Generated by `ai-hats retro <session_id>` (manually) or by the session_end
hook (automatically). Pure facts only — no findings, no proposed_fix.
Analysis happens later in the judge layer over a bundle of session retros.
"""

from __future__ import annotations

from datetime import date
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from .common import SessionArtifacts, SessionLinks, SessionMetrics

SCHEMA_VERSION = "hats-session-retro/v1"


class SessionRetroV1(BaseModel):
    """Descriptive snapshot of ONE session.

    Three categories of content:
    - facts:        metrics + artifacts (objective, machine-extractable)
    - narrative:    summary (one paragraph what was done)
    - observations: free-form notes (optional, only when LLM mode is enabled)

    Findings, proposed fixes, and root cause analysis are deliberately absent —
    they belong to the judge layer (JudgeRetroV1) which analyzes one or more
    session retros via a Bundle.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    schema_: Literal["hats-session-retro/v1"] = Field(..., alias="schema")
    session_id: str = Field(..., min_length=1)
    project: str = Field(..., min_length=1)
    role: str = Field(..., min_length=1)
    date: date
    metrics: SessionMetrics
    summary: str = Field(..., min_length=1, description="What was done — narrative")
    artifacts: SessionArtifacts = Field(default_factory=SessionArtifacts)
    observations: list[str] = Field(
        default_factory=list,
        description="Optional free-form notes (LLM mode only, no schema constraints)",
    )
    links: SessionLinks
