"""ai-hats-rack — minimal backlog kernel (epic HATS-1014, K1 HATS-1020).

Public surface: the kernel, the FSM topology loader, the subscriber/dispatch
contract, the event kinds, plus the K2 doc store (fs-as-truth view + frozen
pins) and project-root resolver. Everything else (worktree, ownership, gates,
hooks) is an extension living outside this package.
"""

from .dispatch import (
    AbortOperation,
    Append,
    BindableSubscriber,
    Delta,
    DispatchContext,
    DispatchRecord,
    FieldOp,
    JournalSink,
    OperationAborted,
    Phase,
    RequiresStatesError,
    Set,
    Subscriber,
    SubscriberOutcome,
    Subscription,
    bind_subscribers,
    validate_requires_states,
)
from .docstore import (
    DocInfo,
    DocStore,
    DocumentNameError,
    FrozenDocumentError,
    FrozenPinDriftError,
    RemoveResult,
    UnknownDocumentError,
)
from .cardschema import (
    CardSchema,
    FieldValidationError,
    RequiredFieldError,
    ResolvedField,
    UnknownValidatorError,
    Validator,
    build_card_schema,
    default_card_schema,
)
from .composition import (
    BoundSubscriber,
    ExtensionFactory,
    UnknownHandlerError,
    build_bound_subscribers,
    build_extensions,
    compose_subscribers,
    stock_factories,
    stock_validators,
)
from .definition import (
    BacklogDefinition,
    BacklogDefinitionError,
    Bindings,
    FieldSpec,
    HandlerRef,
    LegacyLinksOverrideError,
    UnsupportedBacklogKeyError,
    load_backlog,
    resolve_definition,
)
from .events import EdgeEvent, EpicifyEvent, Event, PreDestroyEvent, event_detail
from .fsm import (
    InvalidTransitionError,
    Topology,
    TopologyError,
    UnknownStateError,
    load_topology,
)
from .journal import JsonlJournalSink, read_journal
from .kernel import (
    ForceRequiresReasonError,
    Kernel,
    KernelResult,
    LockTimeoutError,
    TaskExistsError,
    TaskTransition,
    UnknownTaskError,
)
from .linked import (
    DEFAULT_MAX_BYTES,
    CardRow,
    ContextPackage,
    DocRef,
    Inclusion,
    LinkResult,
    LinkView,
    Neighbor,
    SelfLinkError,
    build_context,
    card_filter,
    link,
    scan_cards,
    unlink,
    walk_neighborhood,
)
from .matching import Matcher, compile_matcher, matches
from .models import DeltaFieldError, TaskCard, WorkLogEntry
from .registry import (
    DerivedLinkKindError,
    LinkKind,
    LinksRegistry,
    LinksRegistryError,
    UnknownLinkKindError,
    load_registry,
    resolve_links,
)
from .resolver import (
    NoProjectRootError,
    RackRoot,
    find_project_root,
    load_root,
    resolve_root,
)

__all__ = [
    "DEFAULT_MAX_BYTES",
    "AbortOperation",
    "Append",
    "BacklogDefinition",
    "BacklogDefinitionError",
    "BindableSubscriber",
    "Bindings",
    "BoundSubscriber",
    "CardRow",
    "CardSchema",
    "ContextPackage",
    "Delta",
    "DeltaFieldError",
    "DerivedLinkKindError",
    "DispatchContext",
    "DispatchRecord",
    "DocInfo",
    "DocRef",
    "DocStore",
    "DocumentNameError",
    "EdgeEvent",
    "EpicifyEvent",
    "Event",
    "ExtensionFactory",
    "FieldOp",
    "FieldSpec",
    "FieldValidationError",
    "HandlerRef",
    "ForceRequiresReasonError",
    "FrozenDocumentError",
    "FrozenPinDriftError",
    "Inclusion",
    "InvalidTransitionError",
    "JournalSink",
    "JsonlJournalSink",
    "Kernel",
    "KernelResult",
    "LegacyLinksOverrideError",
    "LinkKind",
    "LinkResult",
    "LinkView",
    "LinksRegistry",
    "LinksRegistryError",
    "LockTimeoutError",
    "Matcher",
    "Neighbor",
    "NoProjectRootError",
    "OperationAborted",
    "Phase",
    "PreDestroyEvent",
    "RackRoot",
    "RemoveResult",
    "RequiredFieldError",
    "RequiresStatesError",
    "ResolvedField",
    "SelfLinkError",
    "Set",
    "Subscriber",
    "SubscriberOutcome",
    "Subscription",
    "TaskCard",
    "TaskExistsError",
    "TaskTransition",
    "Topology",
    "TopologyError",
    "UnknownDocumentError",
    "UnknownHandlerError",
    "UnknownLinkKindError",
    "UnknownStateError",
    "UnknownTaskError",
    "UnknownValidatorError",
    "UnsupportedBacklogKeyError",
    "Validator",
    "WorkLogEntry",
    "bind_subscribers",
    "build_bound_subscribers",
    "build_card_schema",
    "build_context",
    "build_extensions",
    "card_filter",
    "compose_subscribers",
    "compile_matcher",
    "default_card_schema",
    "event_detail",
    "find_project_root",
    "link",
    "load_backlog",
    "load_registry",
    "load_root",
    "load_topology",
    "matches",
    "read_journal",
    "resolve_definition",
    "resolve_links",
    "resolve_root",
    "scan_cards",
    "stock_factories",
    "stock_validators",
    "unlink",
    "validate_requires_states",
    "walk_neighborhood",
]
