"""Self-heal stale legacy-path refs after layout migration (HATS-397).

When ``Assembler._migrate_layout_v4_*`` moves content out of the namespace
ai-hats owns (``.agent/{hooks,rules,skills,backlog,...}/`` →
``<ai_hats_dir>/<class>/...``), tracked user-files in the project may still
hold the OLD paths:

  - ``.claude/settings.json`` PreToolUse hook command paths,
  - ``CLAUDE.md`` / ``GEMINI.md`` prose mentions,
  - runbooks, README, shell wrappers, ansible templates.

The healer scans for those refs after migration and:

  - **Stage A1**: auto-rewrites known structured integration points
    (``.claude/settings*.json``) — always-on.
  - **Stage A2**: auto-rewrites text/markdown files (``*.md`` / ``*.txt`` /
    ``*.j2`` / ``*.sh`` / ``.envrc``), but only if the file is **git-clean**
    (no uncommitted changes). Otherwise → inventory fallback.
  - **Stage B**: writes an inventory file at
    ``<ai_hats_dir>/sessions/audits/<ts>-legacy-refs.md`` listing every ref
    that was not auto-healed.

Trigger: HATS-397, proxmox ``ai-hats self update`` regression where
``.claude/settings.json:11`` referenced ``.agent/hooks/pre_bash_secret_guard.py``
after the file moved to ``<ai_hats_dir>/library/hooks/``.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from .paths import LEGACY_PATH_MAP, ai_hats_dir, audits_dir

# ---------- Data model ----------


@dataclass(frozen=True)
class LegacyRef:
    """One occurrence of a legacy-path string inside a user-managed file.

    Attributes:
        file: Absolute path to the file containing the ref.
        line: 1-based line number (0 for whole-file matches from JSON walk).
        legacy_substr: Exact substring that matched the legacy pattern.
        new_substr: Replacement substring under the new layout.
    """

    file: Path
    line: int
    legacy_substr: str
    new_substr: str


@dataclass
class HealReport:
    """Summary of a heal pass — printed to stderr and returned to callers."""

    healed_json: list[LegacyRef] = field(default_factory=list)
    healed_text: list[LegacyRef] = field(default_factory=list)
    inventoried: list[LegacyRef] = field(default_factory=list)
    inventory_path: Path | None = None

    @property
    def total(self) -> int:
        return len(self.healed_json) + len(self.healed_text) + len(self.inventoried)


# ---------- Configuration ----------

# Stage A1: structured JSON integration points (always auto-healed).
JSON_TARGETS: tuple[str, ...] = (
    ".claude/settings.json",
    ".claude/settings.local.json",
)

# Stage A2: extensions eligible for text-substring auto-heal (gated by
# git-clean check).
TEXT_EXTENSIONS: tuple[str, ...] = (".md", ".txt", ".j2", ".sh")
TEXT_FILENAMES: tuple[str, ...] = (".envrc",)

# Directories that the scanner ignores entirely. Managed ai-hats namespace
# is excluded because (a) it's regenerated by bump for managed parts, and
# (b) historical content under it (retros, audits) may legitimately mention
# old paths as facts-in-time.
SKIP_DIR_NAMES: frozenset[str] = frozenset({
    ".git", "node_modules", "__pycache__", ".venv", "venv", ".mypy_cache",
    ".ruff_cache", ".pytest_cache", "dist", "build", ".tox",
})


# ---------- Regex compilation ----------


def _compile_legacy_pattern() -> re.Pattern[str]:
    """Compile a single regex matching any legacy stem from LEGACY_PATH_MAP.

    Matches the substring ``.agent/<stem>/`` or ``.agent/<file>`` where stem
    is one of ``hooks``/``rules``/``skills``/``backlog``/etc. Excludes new-form
    ``.agent/ai-hats/...`` by requiring the stem to be the segment immediately
    after ``.agent/``.

    The pattern also covers ``.gitlog/`` (the legacy sessions root) and the
    ``.agent/STATE.md`` / ``.agent/.last_backup`` single-file entries.
    """
    stems: set[str] = set()
    file_entries: set[str] = set()
    for legacy in LEGACY_PATH_MAP:
        if legacy == ".gitlog":
            stems.add("gitlog-root")
            continue
        # Strip leading ".agent/" if present
        if legacy.startswith(".agent/"):
            tail = legacy[len(".agent/"):]
            if "/" in tail:
                # Directory-style entry like ".agent/backlog" — use first segment as stem
                stems.add(tail.split("/", 1)[0])
            else:
                # File-style entry like ".agent/STATE.md" — match exact filename
                file_entries.add(tail)
        else:
            # ".gitlog" handled above; should not reach here
            pass
    # Add stems for dir entries that are bare (not nested) like "backlog"
    for legacy in LEGACY_PATH_MAP:
        if legacy.startswith(".agent/") and "/" not in legacy[len(".agent/"):]:
            tail = legacy[len(".agent/"):]
            # Only add as stem if it's a directory in LEGACY_PATH_MAP (we
            # detect by absence of "." — files have extensions or leading dot)
            if "." not in tail:
                stems.add(tail)

    stem_alt = "|".join(re.escape(s) for s in sorted(stems) if s != "gitlog-root")
    file_alt = "|".join(re.escape(f) for f in sorted(file_entries))

    parts: list[str] = []
    if stem_alt:
        # .agent/<stem>/  — stem must be followed by '/'
        parts.append(rf"\.agent/(?:{stem_alt})/")
    if file_alt:
        # .agent/<file>  — followed by word boundary or end
        parts.append(rf"\.agent/(?:{file_alt})\b")
    # .gitlog/ — legacy sessions root
    parts.append(r"\.gitlog/")

    return re.compile("(?:" + "|".join(parts) + ")")


_LEGACY_RE = _compile_legacy_pattern()


def _resolve_new_substr(legacy_substr: str, project_dir: Path) -> str | None:
    """Map a matched legacy substring to its new-layout replacement.

    Returns ``None`` if the match doesn't correspond to a known
    ``LEGACY_PATH_MAP`` entry (defensive — should be unreachable given the
    regex is derived from the same map).
    """
    base = ai_hats_dir(project_dir)
    # Compute project-relative path for new location, since that's what we
    # write into user files (avoids absolute paths in tracked content).
    try:
        new_root_rel = base.relative_to(project_dir).as_posix()
    except ValueError:
        # ai_hats_dir is outside project_dir (env override) — fall back to
        # absolute path. User can rewire if needed.
        new_root_rel = str(base)

    # legacy_substr is like ".agent/hooks/" or ".agent/STATE.md" or ".gitlog/"
    if legacy_substr == ".gitlog/":
        return f"{new_root_rel}/sessions/runs/"
    # Strip trailing slash for lookup
    key = legacy_substr.rstrip("/")
    if key in LEGACY_PATH_MAP:
        _, new_rel = LEGACY_PATH_MAP[key]
        # Match the trailing-slash form of the input
        suffix = "/" if legacy_substr.endswith("/") else ""
        return f"{new_root_rel}/{new_rel}{suffix}"
    return None


# ---------- Scanning ----------


def _is_skipped_dir(d: Path, managed_root: Path) -> bool:
    """True if directory should be skipped during walk."""
    if d.name in SKIP_DIR_NAMES:
        return True
    if ".bak." in d.name:
        return True
    try:
        d.resolve().relative_to(managed_root.resolve())
        return True  # inside <ai_hats_dir>/ — skip
    except ValueError:
        return False


def _walk_candidate_files(project_dir: Path):
    """Yield candidate files for scanning, honoring skip rules."""
    managed_root = ai_hats_dir(project_dir)
    stack: list[Path] = [project_dir]
    while stack:
        d = stack.pop()
        try:
            entries = list(d.iterdir())
        except (OSError, PermissionError):
            continue
        for entry in entries:
            try:
                if entry.is_symlink():
                    continue
                if entry.is_dir():
                    if _is_skipped_dir(entry, managed_root):
                        continue
                    stack.append(entry)
                elif entry.is_file():
                    yield entry
            except OSError:
                continue


def _is_text_candidate(path: Path) -> bool:
    """True if `path` is eligible for Stage A2 text scanning."""
    if path.suffix in TEXT_EXTENSIONS:
        return True
    if path.name in TEXT_FILENAMES:
        return True
    return False


def _is_json_target(path: Path, project_dir: Path) -> bool:
    """True if `path` is a Stage A1 JSON allowlist target."""
    try:
        rel = path.relative_to(project_dir).as_posix()
    except ValueError:
        return False
    return rel in JSON_TARGETS


def _scan_text_file(path: Path, project_dir: Path) -> list[LegacyRef]:
    """Line-by-line scan of a text file for legacy substrings."""
    out: list[LegacyRef] = []
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return out
    for lineno, line in enumerate(content.splitlines(), start=1):
        for match in _LEGACY_RE.finditer(line):
            legacy = match.group(0)
            new = _resolve_new_substr(legacy, project_dir)
            if new is None:
                continue
            out.append(LegacyRef(
                file=path, line=lineno, legacy_substr=legacy, new_substr=new,
            ))
    return out


def _scan_json_strings(value, path: Path, project_dir: Path) -> list[LegacyRef]:
    """Recursively walk a parsed JSON value, emitting LegacyRef for matches."""
    out: list[LegacyRef] = []
    if isinstance(value, str):
        for match in _LEGACY_RE.finditer(value):
            legacy = match.group(0)
            new = _resolve_new_substr(legacy, project_dir)
            if new is None:
                continue
            out.append(LegacyRef(
                file=path, line=0, legacy_substr=legacy, new_substr=new,
            ))
    elif isinstance(value, dict):
        for v in value.values():
            out.extend(_scan_json_strings(v, path, project_dir))
    elif isinstance(value, list):
        for v in value:
            out.extend(_scan_json_strings(v, path, project_dir))
    return out


def _scan_json_file(path: Path, project_dir: Path) -> list[LegacyRef]:
    """Parse JSON, walk strings recursively for legacy substrings."""
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return []
    return _scan_json_strings(data, path, project_dir)


def scan_external_refs(project_dir: Path) -> list[LegacyRef]:
    """Walk `project_dir` and collect every legacy-path ref in user files.

    Excludes managed ai-hats namespace, VCS noise, and backup dirs. JSON
    files in the Stage A1 allowlist are parsed as structured; everything
    else with a known text extension is scanned line-by-line.
    """
    refs: list[LegacyRef] = []
    for path in _walk_candidate_files(project_dir):
        if _is_json_target(path, project_dir):
            refs.extend(_scan_json_file(path, project_dir))
        elif _is_text_candidate(path):
            refs.extend(_scan_text_file(path, project_dir))
    return refs


# ---------- Healing — Stage A1 (JSON) ----------


def _replace_legacy_in_value(value, project_dir: Path) -> tuple[object, int]:
    """Recursively replace legacy substrings inside a parsed JSON value.

    Returns ``(new_value, replacement_count)``.
    """
    if isinstance(value, str):
        new_s, count = _LEGACY_RE.subn(
            lambda m: _resolve_new_substr(m.group(0), project_dir) or m.group(0),
            value,
        )
        return new_s, count
    if isinstance(value, dict):
        new_d: dict = {}
        total = 0
        for k, v in value.items():
            new_v, c = _replace_legacy_in_value(v, project_dir)
            new_d[k] = new_v
            total += c
        return new_d, total
    if isinstance(value, list):
        new_list: list = []
        total = 0
        for v in value:
            new_v, c = _replace_legacy_in_value(v, project_dir)
            new_list.append(new_v)
            total += c
        return new_list, total
    return value, 0


def heal_json_file(path: Path, project_dir: Path) -> int:
    """Rewrite legacy substrings in a JSON file. Returns count of replacements.

    Preserves the original file's trailing newline. Idempotent: a re-run on
    already-healed content returns 0.
    """
    try:
        raw = path.read_text(encoding="utf-8")
        data = json.loads(raw)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return 0
    new_data, count = _replace_legacy_in_value(data, project_dir)
    if count == 0:
        return 0
    new_text = json.dumps(new_data, indent=2, ensure_ascii=False)
    if raw.endswith("\n"):
        new_text += "\n"
    path.write_text(new_text, encoding="utf-8")
    return count


# ---------- Healing — Stage A2 (text) ----------


def is_file_git_clean(file: Path, project_dir: Path) -> bool:
    """True if `file` has no uncommitted changes in git.

    Returns True if the file is untracked-but-not-modified, tracked-clean, or
    if git is unavailable / project isn't a git repo (no safety net, but no
    failure either). Returns False only when git reports modifications.
    """
    try:
        result = subprocess.run(
            ["git", "diff", "--quiet", "--", str(file)],
            cwd=str(project_dir),
            capture_output=True,
            timeout=10,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return True  # git unavailable — don't block heal
    if result.returncode == 0:
        return True  # no diff
    if result.returncode == 1:
        return False  # diff present
    # Other return codes (128 = not a git repo, etc.) — be permissive
    return True


def heal_text_file(path: Path, project_dir: Path) -> int:
    """Rewrite legacy substrings in a text file. Returns replacement count.

    Caller is responsible for invoking ``is_file_git_clean`` first; this
    function blindly applies the rewrite.
    """
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return 0
    new_content, count = _LEGACY_RE.subn(
        lambda m: _resolve_new_substr(m.group(0), project_dir) or m.group(0),
        content,
    )
    if count == 0:
        return 0
    path.write_text(new_content, encoding="utf-8")
    return count


# ---------- Inventory — Stage B ----------


def write_inventory(project_dir: Path, refs: list[LegacyRef]) -> Path | None:
    """Write an audit-log of un-healed refs. Returns the path, or None if empty.

    Output lands under ``<ai_hats_dir>/sessions/audits/<utc_ts>-legacy-refs.md``.
    """
    if not refs:
        return None
    out_dir = audits_dir(project_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(tz=timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out_path = out_dir / f"{ts}-legacy-refs.md"

    by_file: dict[Path, list[LegacyRef]] = {}
    for ref in refs:
        by_file.setdefault(ref.file, []).append(ref)

    lines: list[str] = [
        f"# Legacy reference inventory — {ts}",
        "",
        f"Found {len(refs)} legacy-path ref(s) across {len(by_file)} file(s) "
        "that were not auto-healed.",
        "",
        "Reasons a ref is inventoried instead of auto-fixed:",
        "",
        "- File had uncommitted changes (git-dirty) — to keep your in-flight diff intact.",
        "- File extension not in auto-heal allowlist (`.md` / `.txt` / `.j2` / `.sh` / `.envrc`).",
        "",
        "Apply the substitutions below manually, then commit.",
        "",
    ]
    for file_path in sorted(by_file, key=lambda p: str(p)):
        try:
            rel = file_path.relative_to(project_dir).as_posix()
        except ValueError:
            rel = str(file_path)
        lines.append(f"## `{rel}`")
        lines.append("")
        for ref in sorted(by_file[file_path], key=lambda r: r.line):
            loc = f"L{ref.line}" if ref.line > 0 else "(json)"
            lines.append(
                f"- {loc} | `{ref.legacy_substr}` → `{ref.new_substr}`"
            )
        lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


# ---------- Orchestration ----------


def heal_external_refs(project_dir: Path, *, verbose: bool = True) -> HealReport:
    """Run a full heal pass: scan → A1 (JSON) → A2 (text) → B (inventory).

    Args:
        project_dir: Project root.
        verbose: If True, prints progress + summary lines to stderr. Set False
            in tests to assert on the returned ``HealReport`` instead.

    Returns:
        ``HealReport`` summarizing healed and inventoried refs.
    """
    report = HealReport()
    refs = scan_external_refs(project_dir)
    if not refs:
        return report

    # Group refs by file to amortize file rewrite (one read+write per file).
    by_file: dict[Path, list[LegacyRef]] = {}
    for ref in refs:
        by_file.setdefault(ref.file, []).append(ref)

    for file_path, file_refs in by_file.items():
        if _is_json_target(file_path, project_dir):
            # Stage A1 — always-on
            count = heal_json_file(file_path, project_dir)
            if count > 0:
                report.healed_json.extend(file_refs)
                if verbose:
                    _print_healed(file_path, file_refs, project_dir)
            continue

        if _is_text_candidate(file_path):
            # Stage A2 — gated by git-clean
            if not is_file_git_clean(file_path, project_dir):
                report.inventoried.extend(file_refs)
                continue
            count = heal_text_file(file_path, project_dir)
            if count > 0:
                report.healed_text.extend(file_refs)
                if verbose:
                    _print_healed(file_path, file_refs, project_dir)
            continue

        # Defensive — shouldn't happen given the scanner allowlist
        report.inventoried.extend(file_refs)

    if report.inventoried:
        report.inventory_path = write_inventory(project_dir, report.inventoried)

    if verbose:
        _print_summary(report, project_dir)

    return report


def _print_healed(file_path: Path, refs: list[LegacyRef], project_dir: Path) -> None:
    """Emit per-file 'Healed:' lines to stderr."""
    try:
        rel = file_path.relative_to(project_dir).as_posix()
    except ValueError:
        rel = str(file_path)
    for ref in refs:
        loc = f"L{ref.line}" if ref.line > 0 else "(json)"
        print(
            f"[heal] Healed: {rel} {loc} '{ref.legacy_substr}' → "
            f"'{ref.new_substr}'",
            file=sys.stderr,
        )


def _print_summary(report: HealReport, project_dir: Path) -> None:
    """Emit final summary line to stderr."""
    healed_count = len(report.healed_json) + len(report.healed_text)
    if healed_count:
        print(
            f"[heal] Auto-healed {healed_count} legacy-path ref(s) across "
            f"user-managed files.",
            file=sys.stderr,
        )
    if report.inventory_path:
        try:
            rel = report.inventory_path.relative_to(project_dir).as_posix()
        except ValueError:
            rel = str(report.inventory_path)
        print(
            f"[heal] Manual fixes required for {len(report.inventoried)} "
            f"ref(s) — see {rel}",
            file=sys.stderr,
        )
